import type { Metadata } from "next";
import { Cinzel, Geist, Geist_Mono, Special_Elite } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cinemaDisplay = Cinzel({
  variable: "--font-cinema-display",
  subsets: ["latin"],
  weight: ["500", "700", "900"],
});

const cinemaBody = Special_Elite({
  variable: "--font-cinema-body",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cinemaDisplay.variable} ${cinemaBody.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
